#!/bin/sh

# PROVIDE: UniversalRoyalCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# UniversalRoyalCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable UniversalRoyalCoin service.
# UniversalRoyalCoin_config (path): Set to /usr/local/etc/UniversalRoyalCoin.conf by default.
# UniversalRoyalCoin_user:  The user account UniversalRoyalCoin daemon runs as. It uses 'root' user by default.
# UniversalRoyalCoin_group: The group account UniversalRoyalCoin daemon runs as. It uses 'wheel' group by default.
# UniversalRoyalCoin_datadir (str): Default to "/var/db/UniversalRoyalCoin". Base data directory.

. /etc/rc.subr

name=UniversalRoyalCoin
rcvar=UniversalRoyalCoin_enable

: ${UniversalRoyalCoin_enable:=NO}
: ${UniversalRoyalCoin_config=/usr/local/etc/UniversalRoyalCoin.conf}
: ${UniversalRoyalCoin_datadir=/var/db/UniversalRoyalCoin}
: ${UniversalRoyalCoin_user="root"}
: ${UniversalRoyalCoin_group="wheel"}

required_files=${UniversalRoyalCoin_config}
command=/usr/local/bin/UniversalRoyalCoind
UniversalRoyalCoin_chdir=${UniversalRoyalCoin_datadir}
pidfile="${UniversalRoyalCoin_datadir}/UniversalRoyalCoind.pid"
stop_cmd=UniversalRoyalCoin_stop
command_args="-conf=${UniversalRoyalCoin_config} -datadir=${UniversalRoyalCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

UniversalRoyalCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${UniversalRoyalCoin_datadir}
	[ $? -eq 0 ] && chown -R ${UniversalRoyalCoin_user}:${UniversalRoyalCoin_group} ${UniversalRoyalCoin_datadir}
}

UniversalRoyalCoin_prestart()
{
	if [ ! -d "${UniversalRoyalCoin_datadir}/." ]; then
		UniversalRoyalCoin_create_datadir || return 1
	fi
}

UniversalRoyalCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

UniversalRoyalCoin_stop()
{
    UniversalRoyalCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${UniversalRoyalCoin_config} -datadir=${UniversalRoyalCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
